version: "3.9"

services:
  service-dva:
    image: wiremock/wiremock:2.33.2
    ports:
      - 8080:8080
    volumes:
      - ./lib:/var/wiremock/extensions
      - ./mappings/service-dva:/home/wiremock/mappings
    command:
      - "--verbose"
      - "--global-response-templating"
#      - "--extensions org.wiremock.webhooks.Webhooks"
    networks:
      - networkShared

  service-one:
    image: wiremock/wiremock:2.33.2
    ports:
      - 8081:8080
    volumes:
      - ./lib:/var/wiremock/extensions
      - ./mappings/service-one:/home/wiremock/mappings
    command:
      - "--verbose"
      - "--global-response-templating"
#      - "--extensions org.wiremock.webhooks.Webhooks"
    networks:
      - networkShared

networks:
  networkShared:
    name: network_shared
